const ALL_WEATHER = [
    'Light Wind',
    'Fog',
    'Hail',
    'Heavy Snow',
    'Rain',
    'Sleet',
    'Snow',
    'Cold',
    'Extreme Cold',
    'Extreme Heat',
    'Severe Cold',
    'Severe Heat',
    'Very Hot',
    'Hurricane',
    'Light Wind',
    'Moderate Wind',
    'Severe Wind',
    'Strong Wind',
    'Tornado',
    'Windstorm',
    'Blizzard',
    'Duststorm',
    'Greater Duststorm',
    'Hurricane',
    'Severe Thunderstorm',
    'Snowstorm',
    'Thunderstorm',
    'Aberrant Sky',
    'Acid Rain',
    'Animus Blizzard',
    'Arcane Tempest',
    'Blacksleet',
    'Indigo Fog',
    'Dire Hail',
    'Draconic Clouds',
    'Dragon\'s Breath',
    'Ethereal Fog',
    'Expeditious Tailwind',
    'Firestorm',
    'Gatestorm',
    'Ghoststorm',
    'Hallucinatory Stor',
    'Immuring Sleet',
    'Incendiary Clouds',
    'Ghostly Wind',
    'Luminous Clouds',
    'Prismatic Rain',
    'Skyquake',
    'Solid Fog',
    'Spiderweb Clouds',
    'Starfall Hail',
    'Temporal Wind',
    'Thunder Hail',
    'Whispering Wind',
];


/**
 * Return a random description of the weather.
 */
export const randomWeather = () => {
    return ALL_WEATHER[Math.floor(Math.random() * ALL_WEATHER.length)];
}
