env:
  browser: true
extends: 'eslint:recommended'
rules:
  no-undef:
    - 0
  no-unused-vars:
    - 0
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
