env:
  es6: true
  browser: true
parser: babel-eslint
extends:
  - eslint:recommended
plugins:
  - import
rules:
  no-undef:
    - 0
  no-unused-vars:
    - 0
  indent:
    - error
    - 4
  linebreak-style:
    - 0
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-multiple-empty-lines:
    - error
    - max: 2
      maxEOF: 1
      maxBOF: 0
  sort-imports:
  - error
  - ignoreCase: false
    ignoreMemberSort: false
    memberSyntaxSortOrder: ["none", "all", "multiple", "single"]
parserOptions:
  ecmaVersion: 6
  sourceType: "module"
