export { HealthinessStatusServiceComponent } from './healthiness_component'
export { InspirationStatusServiceComponent } from './inspiration_component'
export { MagicalStatusServiceComponent } from './magical_component'
export { TotalWeightStatusServiceComponent } from './total_weight_component'
export { TrackedStatusServiceComponent } from './tracked_component'