export var DataRepository = {
    /**
     * Convenience function to filter data repository by key
     *
     * @param arrayName: name of array to be queried
     * @param key: the key to filter by
     * @param value: value that key should equal
     */
    filterBy: function(arrayName, key, value){
        return DataRepository[arrayName].filter(function(item, __, _) {
            return item[key] === value;
        });
    },

    pointsOfInterest: {
        "adjectives": [
            "Ancient",
            "Arcane",
            "Ashen",
            "Astral",
            "Azure",
            "Blacksmith's",
            "Blazing",
            "Blighted",
            "Broken",
            "Burning",
            "Bustling",
            "Candlelit",
            "Celestial",
            "Cerulean",
            "Cheerful",
            "Chilling",
            "Cimmerian",
            "Cobblestone",
            "Collapsed",
            "Cozy",
            "Craftsman's",
            "Crimson",
            "Crumbled",
            "Cryptic",
            "Crystal",
            "Cursed",
            "Dank",
            "Darkened",
            "Dazzling",
            "Decaying",
            "Decrepit",
            "Deserted",
            "Desolate",
            "Doomed",
            "Dreaded",
            "Dusky",
            "Dusty",
            "Eerie",
            "Eldritch",
            "Elemental",
            "Emerald",
            "Enchanted",
            "Enigmatic",
            "Ephemeral",
            "Eternal",
            "Ethereal",
            "Everlasting",
            "Fading",
            "Fiery",
            "Fleeting",
            "Forgotten",
            "Forsaken",
            "Friendly",
            "Frostbitten",
            "Frosty",
            "Frozen",
            "Gentle Breeze",
            "Gentle",
            "Gilded",
            "Gleaming",
            "Glistening",
            "Glowing",
            "Golden",
            "Hallowed",
            "Harmonic",
            "Haunted",
            "Haunting",
            "Herbalist's",
            "Hidden",
            "Historic",
            "Illuminated",
            "Illusionary",
            "Infinite",
            "Intricate",
            "Iridescent",
            "Ivory",
            "Lingering",
            "Local",
            "Lost",
            "Luminous",
            "Lustrous",
            "Magnetic",
            "Majestic",
            "Maplewood",
            "Market",
            "Mellow",
            "Moldering",
            "Moonlit",
            "Mournful",
            "Muddy",
            "Mystical",
            "Mystified",
            "Oaken",
            "Obsidian",
            "Ominous",
            "Opulent",
            "Petrified",
            "Phantom",
            "Quaint",
            "Radiant",
            "Rosewood",
            "Ruined",
            "Runic",
            "Rural",
            "Rusted",
            "Rustic",
            "Rustling",
            "Sacred",
            "Sapphire",
            "Scenic",
            "Secret",
            "Serene",
            "Shadowed",
            "Shadowy",
            "Shattered",
            "Shimmering",
            "Shrouded",
            "Silent",
            "Silver",
            "Simple",
            "Smoldering",
            "Solar",
            "Soothing",
            "Spectral",
            "Stalwart",
            "Stormy",
            "Stormy",
            "Sturdy",
            "Sunny",
            "Sylvan",
            "Tailor's",
            "Tangled",
            "Thundering",
            "Thunderous",
            "Timeless",
            "Tranquil",
            "Twilight",
            "Twisted",
            "Verdant",
            "Vibrant",
            "Vivid",
            "Wandering",
            "Whirling",
            "Whispering",
            "Windswept",
            "Wise",
            "Wraithlike",
        ],
        "nouns": [
            "Abyssal Relic",
            "Alcove",
            "Alley",
            "Altar",
            "Amulet",
            "Arcane Hourglass",
            "Archipelago",
            "Arena",
            "Arrow",
            "Astral Compass",
            "Bag",
            "Banner",
            "Barracks",
            "Bastion",
            "Bazaar",
            "Bell",
            "Bones",
            "Book",
            "Bookstand",
            "Bow",
            "Bracelet",
            "Bracer",
            "Brazier",
            "Bridge",
            "Candelabra",
            "Candle",
            "Candlestick",
            "Casket",
            "Catacombs",
            "Cave",
            "Cavern",
            "Celestial Scepter",
            "Chain",
            "Chainmail",
            "Chains",
            "Chalice",
            "Chamber",
            "Charm",
            "Chasm",
            "Chest",
            "Citadel",
            "Cloak",
            "Clock",
            "Cloth",
            "Coffer",
            "Coffin",
            "Cottage",
            "Crown",
            "Crucible",
            "Crypt",
            "Crystal Ball",
            "Crystal",
            "Cursed Dagger",
            "Dagger",
            "Dale",
            "Den",
            "Diadem",
            "Dragon Scale",
            "Drapes",
            "Dreamcatcher",
            "Dungeon",
            "Earrings",
            "Elixir",
            "Emerald Medallion",
            "Empire",
            "Emporium",
            "Enchanted Tapestry",
            "Enclave",
            "Ephemeral Vial",
            "Ethereal Mirror",
            "Expanse",
            "Faded Tapestry",
            "Falls",
            "Feather",
            "Fjord",
            "Flask",
            "Folly",
            "Fortress",
            "Foundry",
            "Fountain",
            "Fresco",
            "Frostfire Crystal",
            "Garden",
            "Gate",
            "Gatehouse",
            "Gem",
            "Gilded Censer",
            "Gilded Coffer",
            "Glade",
            "Glen",
            "Globe",
            "Glove",
            "Gloves",
            "Glowing Rose",
            "Glowstone",
            "Glyph",
            "Goblet",
            "Golden Chalice",
            "Grotto",
            "Grove",
            "Harbor",
            "Harmony Bell",
            "Haven",
            "Headquarters",
            "Hidden Blade",
            "Hideaway",
            "Horn",
            "Hourglass",
            "Idol",
            "Illuminated Manuscript",
            "Illuminated Script",
            "Ingot",
            "Inkwell",
            "Jeweled Box",
            "Key",
            "Labyrinth",
            "Lagoon",
            "Lantern",
            "Library",
            "Lighthouse",
            "Locket",
            "Lodge",
            "Lookout",
            "Loom",
            "Luminous Cloak",
            "Mace",
            "Mallet",
            "Manor",
            "Mantle",
            "Map",
            "Marketplace",
            "Mask",
            "Meadow",
            "Medallion",
            "Military Fort",
            "Mirror",
            "Monolith",
            "Moonlit Veil",
            "Moonstone Pendant",
            "Mosaic Tile",
            "Mosaic",
            "Mural",
            "Mystic Rune",
            "Nexus",
            "Oasis",
            "Obelisk",
            "Observatory",
            "Oil Lamp",
            "Orb",
            "Outpost",
            "Owl Figurine",
            "Palace",
            "Pandora's Box",
            "Pathway",
            "Pedestal",
            "Pendant",
            "Phial",
            "Phoenix Feather",
            "Pinnacle",
            "Pirate Ship",
            "Plaza",
            "Port",
            "Potion",
            "Pouch",
            "Prayer Beads",
            "Quarry",
            "Quarters",
            "Quicksilver Ink",
            "Quill",
            "Quiver",
            "Radiant Quill",
            "Refuge",
            "Relic",
            "Reliquary",
            "Reservoir",
            "Retreat",
            "Ring",
            "Robe",
            "Robes",
            "Rod",
            "Roost",
            "Ruin",
            "Rune",
            "Runed Tablet",
            "Sacred Bowl",
            "Sanctuary",
            "Sanctum",
            "Sands",
            "Sapphire Tiara",
            "Sarcophagus",
            "Scepter",
            "Scroll",
            "Sculpture",
            "Shadows",
            "Shield",
            "Shrine",
            "Sigil",
            "Signet",
            "Silver Scroll",
            "Silvered Dagger",
            "Skull",
            "Soothing Locket",
            "Spire",
            "Staff",
            "Statue",
            "Stellar Globe",
            "Sundial",
            "Sword",
            "Table",
            "Tablet",
            "Talisman",
            "Tavern",
            "Terrace",
            "Throne",
            "Tome",
            "Torch",
            "Tower",
            "Town",
            "Vale",
            "Valley",
            "Vase",
            "Vault",
            "Vellum",
            "Verdant Gemstone",
            "Vestments",
            "Wand",
            "Ward",
            "Watchtower",
            "Whispering Wand",
            "Wisp Lantern",
            "Woods",
            "Worn Tapestry",
            "Woven Rug",
        ]
    }
};
