import ko from 'knockout'

import './ability_scores'
import './actions_toolbar'
import './appearance'
import './armor'
import './equipment_tab'
import './exhibit'
import './exhibit_tab'
import './feat_traits'
import './feats'
import './features'
import './inventory_tab'
import './items'
import './magic_items'
import './other_stats'
import './proficiencies'
import './profile'
import './profile_tab'
import './root'
import './savings_throws'
import './skills'
import './skills_tab'
import './spell_slots'
import './spell_stats'
import './spells'
import './spells_tab'
import './stats'
import './stats_tab'
import './status_line'
import './tracker'
import './traits'
import './treasure'
import './weapons'

ko.applyBindings()